name: smartassistant
description: "Un asistente de negocios inteligente."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.2
  
  url_launcher: ^6.3.0
  
  fl_chart: ^1.1.1

  image_picker: ^1.1.2

  flutter_markdown: ^0.7.3

  cupertino_icons: ^1.0.6
  intl: ^0.20.2

  app_links: ^6.4.1 
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/